project:
  type: book
  output-dir: docs

book:
  title: "Flight Test Engineering Reference Handbook"
  author: "Society of Flight Test Engineers"
  date: 2013-01-01
  date-format: YYYY
  toc: true
  toc-depth: 3
  chapters:
    - index.qmd
    - 01-general.qmd
    - 02-math.qmd
    - 03-earth-atmosphere.qmd
    - 04-pitot-statics.qmd
    - 05-aero.qmd
    - 06-axis-systems.qmd
    - 07-mass-properties.qmd
    - 08-motion-analysis.qmd
    - 09-material-strength.qmd
    - 10-reciprocating-engines.qmd
    - 11-propellers.qmd
    - 12-standardization.qmd
    - 13-acoustics.qmd
    - 14-emc.qmd
    - 15-handling-qualities.qmd
    - 16-rotary-wings.qmd
    - 17-gas-turbine-propulsion.qmd
    - 18-radio-communications.qmd
    - 19-electromagnetic-spectrum.qmd
    - 20-communications-systems.qmd
    - 21-display-guidelines.qmd

bibliography: references.json
link-citations: true

format:
  html:
    theme: cosmo
  pdf:
    cover-image: "media/index/image1.jpg"
    documentclass: scrreprt



