project:
  type: book

book:
  title: "Flight Test Engineering Reference Handbook"
  author: "Society of Flight Test Engineers"
  date: 2013-01-01
  date-format: YYYY
  toc: true
  toc-depth: 1
  chapters:
    - index.qmd
    - 01-general.qmd
    - 02-math.qmd
    - 03-earth-atmosphere.qmd
    - 04-pitot-statics.qmd
    - 05-aero.qmd
    - summary.qmd
    - references.qmd

bibliography: references.json
link-citations: true

format:
  html:
    theme: cosmo
  pdf:
    cover-image: "media/index/image1.jpg"
    documentclass: scrreprt



